### PR TITLE
feat: cjs and esm support

### PR DESCRIPTION
**Pull request by thepassle**
Trying to add support for CSS modules for our app at ING, but I ran into quite some issues with esm/cjs compat. Changing our app to `type: 'module'` is not a realistic option right now, so I figured I'd make a PR to add proper support for both esm and cjs here instead.

This adds an export map so this is a breaking change unfortunately.

Also added some improved handling for edgecases wrt to dynamic imports

### CODE REVIEW

**Comment by calebdwilliams** [comment]
I’m OK with the addition but am hesitant to remove any features that match the spec (although to be honest, I’m not sure if it does, I’ll check here in a few). 

Is there a way to modify this PR to make this behavior opt-in?

**Comment by thepassle** [comment]
> but am hesitant to remove any features that match the spec

What do you mean with this?

For context: Currently the plugin will crash/error on:
```js
import(foo);
import(`./foo/${bar}.json`);
```
and it makes sense, because `import(foo)` can't be bundled/statically analyzed, or you would have to bundle the entire filesystem, because it could be anything. Thats why plugins like https://www.npmjs.com/package/rollup-plugin-dynamic-import-variables exist, which kind of does that (and even that has its limitations). But I felt that might be a bit overkill to support in this plugin, so I thought it was a fair compromise to just ignore these edgecases for now. Im happy to hear your thoughts on it though.

**Comment by calebdwilliams** [comment]
> and it makes sense, because import(foo) can't be bundled/statically analyzed

Good point. It's been a minute since I've been in this code base, I'll take a look again at the code.

**Review by calebdwilliams — APPROVED** [review]
LGTM

**Comment by calebdwilliams** [comment]
This has been released. Current version is 2.1.0.

**Comment by thepassle** [comment]
Thanks 🙂 that means I get to delete a bunch of code tomorrow at work

**Comment by calebdwilliams** [comment]
Always happy to assist in the deletion of code. Thanks for the contributions!

**Pull request merged**
